// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14NdjryTIsqtwPfHYDid26tgfds8DQdQ',
    appId: '1:977939722051:web:89dd5b99273fec578a49f6',
    messagingSenderId: '977939722051',
    projectId: 'castelle-ce64b',
    authDomain: 'castelle-ce64b.firebaseapp.com',
    storageBucket: 'castelle-ce64b.firebasestorage.app',
    measurementId: 'G-5MC8GCYP15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWojyTDMo7dMFF5xQrQOkRfNSjcbooIMg',
    appId: '1:977939722051:android:0933e402731f08098a49f6',
    messagingSenderId: '977939722051',
    projectId: 'castelle-ce64b',
    storageBucket: 'castelle-ce64b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkiCwK6XeiyosXYuYfS33QoBgpioFgCWs',
    appId: '1:977939722051:ios:fa55d9968c73dbd18a49f6',
    messagingSenderId: '977939722051',
    projectId: 'castelle-ce64b',
    storageBucket: 'castelle-ce64b.firebasestorage.app',
    androidClientId: '977939722051-1k6kc6lih0f8o4b0cuh0ufbgrb3m81ec.apps.googleusercontent.com',
    iosClientId: '977939722051-euogqm898t1uf78v4pmt61v4et0kpaq9.apps.googleusercontent.com',
    iosBundleId: 'com.castelleapp.castle48',
  );
}
